/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mach' at '11/11/14 3:18 PM' with Gradle 2.2
 *
 * @author mach, @date 11/11/14 3:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
